---
- name: Install Nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Remove Default site
  ansible.builtin.file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  notify: reload nginx


- name: Deploy tuning snippet
  ansible.builtinj.template:
    src: tuning.conf.j2
    dest: /etc/nginx/conf.d/tune.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload nginx

- name: Deploy application vhost
  ansible.builtinj.template:
    src: app.conf.j2
    dest: /etc/nginx/conf.d/app.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload nginx

- name: Validate full nginx configuration
  ansible.builtin.command: nginx -t
  changed_when: false
  when: not common_is_container

- name: Enable and start nginx
  ansible.builtin.systemd_service:
    name: nginx
    enabled: true
    state: started
  when: not common_is_container