---
keepalived_interface: "{{ ansible_default_ipv4.interface }}"
keepalived_virtual_router_id: 51
keepalived_advert_int: 1
keepalived_state: BACKUP
keepalived_priority: 100
keepalived_auth_pass: "{{ vault_keepalived_auth_pass }}"

keepalived_vip: "{{ vip_address }}"
keepalived_vip_cidr: 24

keepalived_check_script: /usr/local/bin/check_haproxy.sh
keepalived_check_interval: 2
keepalived_check_fall: 2
keepalived_check_rise: 2
keepalived_check_weight: -20