---
- name: Install UFW
  ansible.builtin.package:
    name: ufw
    state: present

- name: Allow inbound TCP ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop: "{{ common_firewall_allowed_tcp }}"

- name: Set default policies
  community.general.ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  loop:
    - { direction: incoming, policy: deny }
    - { direction: outgoing, policy: allow }