---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
  when: not common_is_container

- name: Restart app
  ansible.builtin.systemd_service:
    name: "{{ app_name }}"
    state: restarted
  when: not common_is_container